### ISSUE TITLE
pakcoin windows

### ISSUE THREAD

**Issue by CavinChan** [Pakcoin-project/pakcoinold#4]
For some reason, not synchronized

**Comment by drwatson84** [comment]
It is synchronising. Please tell us the exact error you face.

**Comment by lemcoin** [comment]
The same, I open the wallet, synchronization does not go

**Comment by drwatson84** [comment]
Does it close instantly after you open it? If so, then your Antivirus is blocking the app.
Whitelist the app and then open again.
If there is some sort of error you may share the screenshot or error.

**Comment by drwatson84** [comment]
No response received, closing issue now.
